//
//  BreedsListEnum.swift
//  what-a-dog
//
//  Created by Eduardo Dini on 01/06/22.
//

import Foundation

enum BreedsListEnum: String {
    case affenpinscher = "Affenpinscher"
    case afghanHound = "Afghan Hound"
    case africanHuntingDog = "African Hunting Dog"
    case airedaleTerrier = "Airedale Terrier"
    case alaskanMalamute = "Alaskan Malamute"
    case americanEskimoDog = "American Eskimo Dog"
    case americanFoxhound = "American Foxhound"
    case americanStaffordshireTerrier = "American Staffordshire Terrier"
    case americanWaterSpaniel = "American Water Spaniel"
    case appenzellerSennenhund = "Appenzeller Sennenhund"
    case australianKelpie = "Australian Kelpie"
    case australianTerrier = "Australian Terrier"
    case basenji = "Basenji"
    case bassetHound = "Basset Hound"
    case beagle = "Beagle"
    case beardedCollie = "Bearded Collie"
    case bedlingtonTerrier = "Bedlington Terrier"
    case belgianMalinois = "Belgian Malinois"
    case berneseMountainDog = "Bernese Mountain Dog"
    case blackAndTanCoonhound = "Black and Tan Coonhound"
    case bloodhound = "Bloodhound"
    case bluetickCoonhound = "Bluetick Coonhound"
    case borderCollie = "Border Collie"
    case borderTerrier = "Border Terrier"
    case bostonTerrier = "Boston Terrier"
    case bouvierDesFlandres = "Bouvier des Flandres"
    case boxer = "Boxer"
    case briard = "Briard"
    case brittany = "Brittany"
    case bullmastiff = "Bullmastiff"
    case cairnTerrier = "Cairn Terrier"
    case cardiganWelshCorgi = "Cardigan Welsh Corgi"
    case chesapeakeBayRetriever = "Chesapeake Bay Retriever"
    case chowChow = "Chow Chow"
    case clumberSpaniel = "Clumber Spaniel"
    case cockerSpaniel = "Cocker Spaniel"
    case dobermanPinscher = "Doberman Pinscher"
    case englishSetter = "English Setter"
    case englishSpringerSpaniel = "English Springer Spaniel"
    case frenchBulldog = "French Bulldog"
    case germanShepherdDog = "German Shepherd Dog"
    case germanShorthairedPointer = "German Shorthaired Pointer"
    case giantSchnauzer = "Giant Schnauzer"
    case goldenRetriever = "Golden Retriever"
    case gordonSetter = "Gordon Setter"
    case greatDane = "Great Dane"
    case greatPyrenees = "Great Pyrenees"
    case irishSetter = "Irish Setter"
    case irishTerrier = "Irish Terrier"
    case irishWolfhound = "Irish Wolfhound"
    case italianGreyhound = "Italian Greyhound"
    case japaneseChin = "Japanese Chin"
    case keeshond = "Keeshond"
    case komondor = "Komondor"
    case kuvasz = "Kuvasz"
    case labradorRetriever = "Labrador Retriever"
    case leonberger = "Leonberger"
    case lhasaApso = "Lhasa Apso"
    case maltese = "Maltese"
    case miniaturePinscher = "Miniature Pinscher"
    case miniatureSchnauzer = "Miniature Schnauzer"
    case newfoundland = "Newfoundland"
    case norfolkTerrier = "Norfolk Terrier"
    case norwichTerrier = "Norwich Terrier"
    case oldEnglishSheepdog = "Old English Sheepdog"
    case papillon = "Papillon"
    case pekingese = "Pekingese"
    case pembrokeWelshCorgi = "Pembroke Welsh Corgi"
    case pomeranian = "Pomeranian"
    case poodleMiniature = "Poodle (Miniature)"
    case poodleToy = "Poodle (Toy)"
    case pug = "Pug"
    case redboneCoonhound = "Redbone Coonhound"
    case rhodesianRidgeback = "Rhodesian Ridgeback"
    case rottweiler = "Rottweiler"
    case saintBernard = "Saint Bernard"
    case saluki = "Saluki"
    case samoyed = "Samoyed"
    case schipperke = "Schipperke"
    case scottishDeerhound = "Scottish Deerhound"
    case scottishTerrier = "Scottish Terrier"
    case shetlandSheepdog = "Shetland Sheepdog"
    case shihTzu = "Shih Tzu"
    case siberianHusky = "Siberian Husky"
    case silkyTerrier = "Silky Terrier"
    case softCoatedWheatenTerrier = "Soft Coated Wheaten Terrier"
    case staffordshireBullTerrier = "Staffordshire Bull Terrier"
    case standardSchnauzer = "Standard Schnauzer"
    case tibetanMastiff = "Tibetan Mastiff"
    case tibetanTerrier = "Tibetan Terrier"
    case toyFoxTerrier = "Toy Fox Terrier"
    case treeingWalkerCoonhound = "Treeing Walker Coonhound"
    case vizsla = "Vizsla"
    case weimaraner = "Weimaraner"
    case welshSpringerSpaniel = "Welsh Springer Spaniel"
    case westHighlandWhiteTerrier = "West Highland White Terrier"
    case whippet = "Whippet"
    case wireFoxTerrier = "Wire Fox Terrier"
    case yorkshireTerrier = "Yorkshire Terrier"
}

extension BreedsListEnum: CaseIterable {}
